### PR TITLE
Feat: Custom Panels URLs (ex: subdomains or any url)

### PR DESCRIPTION
**Pull request by Saifallak**
i need to hide current panel so thats https://github.com/bezhanSalleh/filament-panel-switch/pull/13/commits/30c9e008500572e7c986386a6ff5308ec428261c

also need to override the url ( https://github.com/bezhanSalleh/filament-panel-switch/pull/13/commits/1a14c32fa382c846646922344f35ca69189d9530 ), because in https://github.com/bezhanSalleh/filament-panel-switch/pull/7#issuecomment-1768048070 it breaked my app, because i have each panel on diff, sub domain, so this must not be relative at all.

### CODE REVIEW

**Comment by Saifallak** [comment]
i need to hide current panel so thats https://github.com/bezhanSalleh/filament-panel-switch/pull/13/commits/30c9e008500572e7c986386a6ff5308ec428261c

**Comment by Saifallak** [comment]
also need to override the url, because in https://github.com/bezhanSalleh/filament-panel-switch/pull/7#issuecomment-1768048070 it breaked my app, because i have each panel on diff, sub domain, so this must not be relative at all.

**Comment by Saifallak** [comment]
Could you check this? @bezhanSalleh

**Comment by bezhanSalleh** [comment]
> Could you check this? @bezhanSalleh 

You can exclude the current panel already via `excludes()` method. So, no need for a new method.

So for the paths, what are you doing when you say you have the panels on different subdomains?

I need a little bit of context here to see that there might be a better way. been busy with vue for past couple of months so not really up-to date with the new filament features.

**Comment by Saifallak** [comment]
for excluding current panel, didn't think that (excludes)[https://github.com/bezhanSalleh/filament-panel-switch/blob/521a74a2020159d9ead5379b8de11bf39b901609/src/PanelSwitch.php#L96C21-L96C29] access closure, okay ill revert this change.

----

i have panels like the following:

`admin.example.com`
`client.example.com`
`dev.example.com`

i need to switch between them.

**Comment by Saifallak** [comment]
>  been busy with vue for past couple of months so not really up-to date with the new filament features.

no hurry, take your time.

**Comment by bezhanSalleh** [comment]
> for excluding current panel, didn't think that [excludes](https://github.com/bezhanSalleh/filament-panel-switch/blob/521a74a2020159d9ead5379b8de11bf39b901609/src/PanelSwitch.php#L96C21-L96C29) access closure, okay ill revert this change.
> 
> i have panels like the following:
> 
> `admin.example.com` `client.example.com` `dev.example.com`
> 
> i need to switch between them.

ok, i think i have the time to make a release. So, show me the panel configurations. or you can just take the demo app for instance.
the main domain is say `filament-demo.test` so the app domain would be `app.filament-demo.test` if so how would you configure your panels for them?

or if this doesn't make since give me an example using the code your implemented for urls. how would you use them then.

**Comment by Saifallak** [comment]
Panel 1:

```php
public function panel(Panel $panel): Panel
    {
        return $panel
            ->id('admin')
            ->path('')
            ->domain('cp.' . parse_url(config('app.url'))['host'])
            ->authGuard('admins')
            ->colors([
                'primary' => Color::Blue,
            ]);
```


Panel 2:

```php
public function panel(Panel $panel): Panel
    {
        return $panel
            ->id('dev')
            ->path('')
            ->domain('dev.' . parse_url(config('app.url'))['host'])
            ->authGuard('admins')
            ->colors([
                'primary' => Color::Red,
            ]);
```


Panel 3:

```php
public function panel(Panel $panel): Panel
    {
        return $panel
            ->id('console')
            ->path('')
            ->domain('console.' . parse_url(config('app.url'))['host'])
            ->authGuard('admins')
            ->colors([
                'primary' => Color::Green,
            ]);
```

I just wanted to use URLs like the following:
because it doesn't work out of the box

```php
PanelSwitch::configureUsing(function (PanelSwitch $panelSwitch) {
            $panelSwitch
                ->urls([
                    'admin' => 'https://' . 'cp.' . parse_url(config('app.url'))['host'],
                    'dev' => 'https://' . 'dev.' . parse_url(config('app.url'))['host'],
                    'console' => 'https://' . 'console.' . parse_url(config('app.url'))['host'],
                ]);
        });
```

**Comment by bezhanSalleh** [comment]
this should be handled by the plugin automatically. which now it does 😎.
update to the latest release and let me know if you face any issues

**Comment by Saifallak** [comment]
@bezhanSalleh okay it works, thanks ♥

btw, is there a way to show this switch on auth screens too ?

**Pull request closed without merging**
