### PR TITLE
[Feature] Handle Panel Domains

### LINKED ISSUE #14: [Bug]: Top navigation breaks panel selection modal
### What happened?

Hi.

Having the same issue as #12  and the suggestion (use another render hook) makes no difference.

It seems that when a panel uses `->topNavigation()`, although the Panel Switch button is there (wherever you hook it to), clicking it does not show the panel selection modal.

### How to reproduce the bug

Fresh installation, just add `->topNavigation()`to the panel in App\Providers\Filament\AdminPanelProvider and try it.

### Package Version

1

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

macOS

### Notes

_No response_

### PR DESCRIPTION
**Pull request by bezhanSalleh**
Fixes #14
Closes #13

### CODE REVIEW

**Comment by andrewdwallo** [comment]
@bezhanSalleh This PR did not fix #14 or #12. Your suggestion or "fix" to use a different render hook does not work as well. The only thing that does work with `topNavigation` enabled is using the `simple` method for the panel switch, nothing else. 

When using `topNavigation`, clicking on the button to open the panel switch modal does absolutely nothing.

**Comment by bezhanSalleh** [comment]
There was supposed to be an issue regarding what the title of the PR says weird 🤔. Anyhow, I haven't looked into top navigation issue and this is for what it says. Apologies for misleading comment.

**Comment by andrewdwallo** [comment]
Sorry. I was just commenting here because I noticed that you closed both of the issues that I mentioned above saying that this PR fixes those issues. That is what I was commenting about. I wasn't commenting about the "Handle Domains" feature. 

Anyways, I found the fix for both #14 and #12 and will be submitting a PR for it shortly. Thanks.

**Comment by bezhanSalleh** [comment]
Sweet,I have reopened them so be sure to mention it in your PR.

**Comment by andrewdwallo** [comment]
Sounds good!

**Pull request merged**
